name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Selenium Server
        run: wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar -O selenium-server.jar

      - name: Start Selenium Server HUB
        run: |
                java -jar selenium-server.jar -role hub &
                sleep 10

      - name: Start Selenium Server node
        run: |
            java -jar selenium-server.jar -role node -hub http://localhost:4444/grid/register -port 5555 &
            sleep 10

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Run API tests
        run: |
          python -m unittest API_tests_on_GamePower_and_UI_tests_on_YouTube/tests/api_test/test_runner.py
#      - name: Run UI tests
#        run: |
#          python -m unittest API_tests_on_GamePower_and_UI_tests_on_YouTube/tests/ui_test/run_all_tests.py


#      - name: Download Selenium Server
#          run: wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar -O selenium-server.jar







#            - name: Check Selenium Grid Hub Status
#              run: |
#                curl http://localhost:4444/grid/api/hub
#                echo "Selenium Grid Hub status checked."
